 const HomePosts = [
    {
        id: 1,
        title: 'Welcome to the Docs',
        content_image:'https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGVjaHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
        content: 'The Docs are a great place to get started, with a focus on API usage, components, and code examples.' ,
        date: '20 July, 2019',
        like_Number: 10,
        comment_Number: 4,
        share_Number: 0,
        userImage: 'https://media.istockphoto.com/photos/learn-to-love-yourself-first-picture-id1291208214?b=1&k=20&m=1291208214&s=170667a&w=0&h=sAq9SonSuefj3d4WKy4KzJvUiLERXge9VgZO-oqKUOo=',
        userName: 'John Doe',
        userId: 1,
        userEmail: 'starlordflash@gmail.com',
        up_vote: 50,
        down_vote: 5,
        comments: [
            {
                user_id: 1,
                userImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aHVtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Programming is fun so lets do it',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 2,
                userImage: 'https://images.unsplash.com/photo-1530695440407-21fef47230b1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGh1bWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Phyton is a great language',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 3,
                userImage: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8aHVtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Javascript is a scripting language that can be used to create dynamic web pages, run programs, and build interactive applications.',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
        ],




    },



    {
        id: 2,
        title: 'Welcome to the Docs',
        content_image:'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
        content: 'The Docs are a great place to get started, with a focus on API usage, components, and code examples.' ,
        date: '20 July, 2010',
        like_Number: 0,
        comment_Number: 0,
        share_Number: 0,
        userImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cHJvZmlsZSUyMHBpY3R1cmV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
        userName: 'John Doe',
        userId: 2,
        userEmail: 'arinze@gmail.com',
        up_vote: 50,
        down_vote: 5,
        comments: [
            {
                user_id: 1,
                userImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cHJvZmlsZSUyMHBpY3R1cmV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Programming is fun so lets do it',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 2,
                userImage: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8cHJvZmlsZSUyMHBpY3R1cmV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Phyton is a great language',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 3,
                userImage: 'https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samueljoe@gmail.com',
                comment: 'Javascript is a scripting language that can be used to create dynamic web pages, run programs, and build interactive applications.',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
        ],


    },

    {
        id: 3,
        title: 'Welcome to the Docs',
        content_image:'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
        content: 'The Docs are a great place to get started, with a focus on API usage, components, and code examples.' ,
        date: '20 July, 2010',
        like_Number: 0,
        comment_Number: 0,
        share_Number: 0,
        userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        userName: 'John Doe',
        userId: 2,
        userEmail: 'arinze@gmail.com',
        up_vote: 50,
        down_vote: 5,
        comments: [
            {
                user_id: 1,
                userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Programming is fun so lets do it',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 2,
                userImage: 'https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'Sam kelvin',
                userId: 1,
                userEmail: 'samuel@niger.ng',
                comment: 'Phyton is a great language',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 3,
                userImage: 'https://unsplash.com/photos/4Z4NHcSfph4',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samueljoe@gmail.com',
                comment: 'Javascript is a scripting language that can be used to create dynamic web pages, run programs, and build interactive applications.',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
        ],


    },

    {
        id: 4,
        title: 'Welcome to the Docs',
        content_image:'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
        content: 'The Docs are a great place to get started, with a focus on API usage, components, and code examples.' ,
        date: '20 July, 2010',
        like_Number: 0,
        comment_Number: 0,
        share_Number: 0,
        userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        userName: 'John Doe',
        userId: 2,
        userEmail: 'arinze@gmail.com',
        up_vote: 50,
        down_vote: 5,
        comments: [
            {
                user_id: 1,
                userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Programming is fun so lets do it',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 2,
                userImage: 'https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'Sam kelvin',
                userId: 1,
                userEmail: 'samuel@niger.ng',
                comment: 'Phyton is a great language',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 3,
                userImage: 'https://unsplash.com/photos/4Z4NHcSfph4',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samueljoe@gmail.com',
                comment: 'Javascript is a scripting language that can be used to create dynamic web pages, run programs, and build interactive applications.',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
        ],


    },

    {
        id: 5,
        title: 'Welcome to the Docs',
        content_image:'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
        content: 'The Docs are a great place to get started, with a focus on API usage, components, and code examples.' ,
        date: '20 July, 2010',
        like_Number: 0,
        comment_Number: 0,
        share_Number: 0,
        userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        userName: 'John Doe',
        userId: 2,
        userEmail: 'arinze@gmail.com',
        up_vote: 50,
        down_vote: 5,
        comments: [
            {
                user_id: 1,
                userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samuel joe',
                comment: 'Programming is fun so lets do it',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 2,
                userImage: 'https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
                userName: 'Sam kelvin',
                userId: 1,
                userEmail: 'samuel@niger.ng',
                comment: 'Phyton is a great language',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
            {
                user_id: 3,
                userImage: 'https://unsplash.com/photos/4Z4NHcSfph4',
                userName: 'John Doe',
                userId: 1,
                userEmail: 'samueljoe@gmail.com',
                comment: 'Javascript is a scripting language that can be used to create dynamic web pages, run programs, and build interactive applications.',
                date: '20 July, 2019',
                up_vote: 20,
                down_vote: 5,
            },
        ],


    },
   


];
export default  HomePosts;