export const type = {
  CREATE_USER: "CREATE_USER",
  GET_QUESTIONS:"GET_QUESTIONS",
  GET_EXPERIENCE:"GET_EXPERIENCE",
  GET_PROJECT:"GET_PROJECT",
  GET_EDUCATION:"GET_EDUCATION",
  GET_SKILL:"GET_SKILL",
  GET_AWARDS:"GET_AWARDS",
  GET_CERTIFICATES:"GET_CERTIFICATES",
  START_LOADING:"START_LOADING",
  STOP_LOADING:"STOP_LOADING",
};
